# .github/workflows/deploy-pre.yml
name: Deploy Frontend to Prep

on:
  push:
    branches:
      - preprod

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      
      - name: Update Repository
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az vm run-command invoke \
              --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
              --name ${{ secrets.AZURE_VM_NAME }} \
              --command-id RunShellScript \
              --scripts '
                echo "Iniciando actualización del repositorio..."
                
                cd /home/innotech/hica/frontend/frontend-hica || exit 1
                echo "Directorio actual: $(pwd)"
                
                echo "Estado actual del repositorio:"
                git status
                
                echo "Obteniendo cambios remotos..."
                git fetch origin preprod || exit 1
                
                echo "Cambiando a rama preprod..."
                git checkout preprod || exit 1
                
                echo "Actualizando rama preprod..."
                git pull origin preprod || exit 1
                
                echo "Log del último commit:"
                git log -1
                
                echo "Actualización completada."
              '